INFO 2025-03-24 23:57:27,205 task_logger Запуск задачи update_wallet_statistics_task с параметрами: args=(<@task: src.infra.celery.tasks.update_wallet_statistics_task of core at 0x7f19c23d0390>,), kwargs={}
INFO 2025-03-24 23:57:27,374 wallet_statistic_updater Начинаем получение кошельков из БД
ERROR 2025-03-24 23:57:27,407 task_logger Ошибка при выполнении задачи update_wallet_statistics_task:  | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 51, in update_wallet_statistics_task
    asyncio.run(process_update_wallet_statistics())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 335, in process_update_wallet_statistics
    await receive_wallets_from_db(
  File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 49, in receive_wallets_from_db
    wallets: list[Wallet] = await SQLAlchemyWalletRepository(session).get_wallets_for_update_stats(count=count)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/wallet.py", line 132, in get_wallets_for_update_stats
    raise NotImplementedError
NotImplementedError

INFO 2025-03-24 23:58:39,684 task_logger Запуск задачи update_wallet_statistics_task с параметрами: args=(<@task: src.infra.celery.tasks.update_wallet_statistics_task of core at 0x7f82a7d040d0>,), kwargs={}
INFO 2025-03-24 23:58:39,798 wallet_statistic_updater Начинаем получение кошельков из БД
ERROR 2025-03-24 23:58:39,813 task_logger Ошибка при выполнении задачи update_wallet_statistics_task:  | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 51, in update_wallet_statistics_task
    asyncio.run(process_update_wallet_statistics())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 335, in process_update_wallet_statistics
    await receive_wallets_from_db(
  File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 49, in receive_wallets_from_db
    wallets: list[Wallet] = await SQLAlchemyWalletRepository(session).get_wallets_for_update_stats(count=count)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/wallet.py", line 132, in get_wallets_for_update_stats
    raise NotImplementedError
NotImplementedError

INFO 2025-03-25 00:06:02,197 task_logger Запуск задачи update_wallet_statistics_task с параметрами: args=(<@task: src.infra.celery.tasks.update_wallet_statistics_task of core at 0x7fe3faa2b950>,), kwargs={}
INFO 2025-03-25 00:06:02,318 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-25 00:06:04,726 wallet_statistic_updater Получили 89531 кошельков из БД | Время: 0:00:02.407781
ERROR 2025-03-25 00:06:07,486 task_logger Ошибка при выполнении задачи update_wallet_statistics_task: unhandled errors in a TaskGroup (1 sub-exception) |   + Exception Group Traceback (most recent call last):
  |   File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
  |     result = func(*args, **kwargs)
  |              ^^^^^^^^^^^^^^^^^^^^^
  |   File "/app/src/infra/celery/tasks.py", line 51, in update_wallet_statistics_task
  |     asyncio.run(process_update_wallet_statistics())
  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 340, in process_update_wallet_statistics
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 104, in fetch_wallets_related_data
    |     await asyncio.gather(*tasks)
    |   File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 131, in _fetch_related_data
    |     wallet_tokens_dict[wt["wallet_id"]].append(wt)
    |                        ~~^^^^^^^^^^^^^
    | TypeError: 'WalletToken' object is not subscriptable
    +------------------------------------

INFO 2025-03-25 00:08:18,812 task_logger Запуск задачи update_wallet_statistics_task с параметрами: args=(<@task: src.infra.celery.tasks.update_wallet_statistics_task of core at 0x7f5bae088250>,), kwargs={}
INFO 2025-03-25 00:08:18,921 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-25 00:08:21,277 wallet_statistic_updater Получили 89531 кошельков из БД | Время: 0:00:02.355636
ERROR 2025-03-25 00:08:23,423 task_logger Ошибка при выполнении задачи update_wallet_statistics_task: unhandled errors in a TaskGroup (1 sub-exception) |   + Exception Group Traceback (most recent call last):
  |   File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
  |     result = func(*args, **kwargs)
  |              ^^^^^^^^^^^^^^^^^^^^^
  |   File "/app/src/infra/celery/tasks.py", line 51, in update_wallet_statistics_task
  |     asyncio.run(process_update_wallet_statistics())
  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 340, in process_update_wallet_statistics
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 181, in update_wallets
    |     raise exception
    |   File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 218, in _update_wallets_data
    |     await asyncio.gather(
    |   File "/app/src/application/etl/wallet_statistic_updaters/wallet_statistic_updater.py", line 260, in _update_wallets
    |     await SQLAlchemyWalletRepository(session).bulk_update(
    |   File "/app/src/infra/db/sqlalchemy/repositories/generic_repository.py", line 114, in bulk_update
    |     fields_to_update = fields - excluded_fields  # Поля для обновления
    |                        ~~~~~~~^~~~~~~~~~~~~~~~~
    | TypeError: unsupported operand type(s) for -: 'set' and 'dict'
    +------------------------------------

INFO 2025-03-25 00:09:43,303 task_logger Запуск задачи update_wallet_statistics_task с параметрами: args=(<@task: src.infra.celery.tasks.update_wallet_statistics_task of core at 0x7f5b57d80050>,), kwargs={}
INFO 2025-03-25 00:09:43,412 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-25 00:09:45,762 wallet_statistic_updater Получили 89531 кошельков из БД | Время: 0:00:02.349381
INFO 2025-03-25 00:10:17,962 wallet_statistic_updater Процесс обновления кошельков завершен! | Кол-во: 300000 | Токенов: 135450 | Время: 34.55 сек | В минуту: (520981 / 235223)
INFO 2025-03-25 00:10:17,963 wallet_statistic_updater Суммарная статистика | Кошельков: 300000 | Токенов: 135450 | Время: 0.58 мин | В минуту: (520981 / 235223)
INFO 2025-03-25 00:10:17,963 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-25 00:10:20,447 wallet_statistic_updater Получили 89531 кошельков из БД | Время: 0:00:02.483339
INFO 2025-03-25 00:10:55,007 wallet_statistic_updater Процесс обновления кошельков завершен! | Кол-во: 300000 | Токенов: 135450 | Время: 37.04 сек | В минуту: (485913 / 219389)
INFO 2025-03-25 00:10:55,018 wallet_statistic_updater Суммарная статистика | Кошельков: 600000 | Токенов: 270900 | Время: 1.19 мин | В минуту: (502836 / 227030)
INFO 2025-03-25 00:10:55,018 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-25 00:10:57,554 wallet_statistic_updater Получили 89531 кошельков из БД | Время: 0:00:02.536308
INFO 2025-03-25 00:11:30,170 wallet_statistic_updater Процесс обновления кошельков завершен! | Кол-во: 300000 | Токенов: 135450 | Время: 35.15 сек | В минуту: (512057 / 231194)
INFO 2025-03-25 00:11:30,170 wallet_statistic_updater Суммарная статистика | Кошельков: 900000 | Токенов: 406350 | Время: 1.78 мин | В минуту: (505873 / 228401)
INFO 2025-03-25 00:11:30,171 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-25 00:11:32,690 wallet_statistic_updater Получили 89531 кошельков из БД | Время: 0:00:02.519145
INFO 2025-03-25 00:41:23,450 wallet_statistic_buygt15k_updater Получили 1 кошельков из БД | Время: 0:00:00.022353
INFO 2025-03-25 00:41:23,547 wallet_statistic_buygt15k_updater Обновили кошельки в базе! Кошельков: 1 | Токен-статистик: 10 | Время: 0:00:00.097350 
INFO 2025-03-25 00:52:04,490 wallet_statistic_buygt15k_updater Получили 8 кошельков из БД | Время: 0:00:00.014068
INFO 2025-03-25 00:52:04,714 wallet_statistic_buygt15k_updater Обновили кошельки в базе! Кошельков: 8 | Токен-статистик: 20 | Время: 0:00:00.224048 
INFO 2025-03-25 00:52:55,893 wallet_statistic_buygt15k_updater Получили 8 кошельков из БД | Время: 0:00:00.014107
INFO 2025-03-25 00:55:02,408 wallet_statistic_buygt15k_updater Получили 8 кошельков из БД | Время: 0:00:00.014355
INFO 2025-03-25 00:55:02,646 wallet_statistic_buygt15k_updater Обновили кошельки в базе! Кошельков: 8 | Токен-статистик: 20 | Время: 0:00:00.237613 
INFO 2025-03-25 02:05:23,146 wallet_statistic_buygt15k_updater Получили 1 кошельков из БД | Время: 0:00:00.024776
INFO 2025-03-25 02:05:23,254 wallet_statistic_buygt15k_updater Обновили кошельки в базе! Кошельков: 1 | Время: 0:00:00.107673
INFO 2025-03-27 02:01:15,360 task_logger Запуск задачи update_wallet_statistics_task с параметрами: args=(<@task: src.infra.celery.tasks.update_wallet_statistics_task of core at 0x7f84d54be8d0>,), kwargs={}
INFO 2025-03-27 02:01:15,362 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-27 02:01:18,725 wallet_statistic_updater Получили 89531 кошельков из БД | Время: 0:00:03.363078
INFO 2025-03-27 02:01:52,709 wallet_statistic_updater Процесс обновления кошельков завершен! | Кол-во: 300000 | Токенов: 135450 | Время: 37.35 сек | В минуту: (481959 / 217604)
INFO 2025-03-27 02:01:52,709 wallet_statistic_updater Суммарная статистика | Кошельков: 300000 | Токенов: 135450 | Время: 0.62 мин | В минуту: (481959 / 217604)
INFO 2025-03-27 02:01:52,710 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-27 02:01:55,535 wallet_statistic_updater Получили 89531 кошельков из БД | Время: 0:00:02.825594
INFO 2025-03-27 02:02:13,317 task_logger Запуск задачи update_wallet_statistics_task с параметрами: args=(<@task: src.infra.celery.tasks.update_wallet_statistics_task of core at 0x7f4b1d870290>,), kwargs={}
INFO 2025-03-27 02:02:13,319 wallet_statistic_updater Начинаем получение кошельков из БД
INFO 2025-03-27 02:02:22,059 wallet_statistic_updater Получили 300000 кошельков из БД | Время: 0:00:08.740148
